feat: "lpa"
config_variant: False
save_dir: ""
force_delete: False
intermediate_data_dir: "intermediate_CP"
preprocess_config: "preprocess_config_default.yml"
train_config: "train_config_cross_project.yml"
translate_config: "translate_config_default.yml"
augment: 3
num_pas: -1
