all_prevassign: False
batch_size: 32
valid_batch_size: 10
dec_layers: 2
dec_rnn_size: 256
early_stopping: 20
enc_layers: 2
enc_rnn_size: 256
encoder_type: brnn
copy_attn: False
consist_reg: False
gpu_ranks:
- 0
keep_checkpoint: 1
optim: adagrad
pool_method: fc
learning_rate: 0.001
report_every: 25
rnn_type: GRU
global_attention: general
save_checkpoint_steps: 75
src_types:
- l
- type
src_word_vec_size: 128
tgt_word_vec_size: 128
train_steps: 60000
valid_steps: 75
world_size: 1
